name = "cf-debugging-worker" # todo
main = "./src/index.ts"
compatibility_date = "2022-05-03"
logpush = true
usage_model = "unbound"
node_compat = true

routes = [
  { pattern = "<your-domain>", custom_domain = true },
]

[placement]
mode = "smart"